### ISSUE TITLE
预览白屏

### ISSUE THREAD

**Issue by ZSK-CRS** [RmondJone/AndroidCamera#3]
在Android 8.0以上 我的是OPPO8.1的系统预览白屏

**Comment by Born-alone** [comment]
也是白屏 解决了么？

**Comment by ZSK-CRS** [comment]
> 也是白屏 解决了
解决了，他的问题在于设置的预览尺寸和设置的图片尺寸 在一些设备上没有 ，他选的最佳的尺寸的方法不对 你随便在其他的文章上找一下设置最佳尺寸的方法 替换一下就可以了 但是这个还有很大的问题

**Comment by RmondJone** [comment]
还有啥问题，一并反馈下，我抽空一起解决了
