### ISSUE TITLE
图片尺寸问题

### ISSUE THREAD

**Issue by GIVEWAYTO** [RmondJone/AndroidCamera#8]
你好，请问是在哪里设置了输出图片的尺寸？我用的是小米8 分辩率是1080x2248，直接运行代码后(全屏拍摄)，图片输出尺寸却为3024x4032。请问需要修改哪里 谢谢。

**Comment by RmondJone** [comment]
CameraPreview#surfaceCreated，里面有设置图片尺寸的地方，但是一般不建议改这边，这边都是根据设备自适应的最佳尺寸，要改图片大小，可以统一在拍照完成那边修改尺寸

**Comment by GIVEWAYTO** [comment]
是的，我也同意你的观点，但是现在在未修改有效代码的情况下，全屏拍摄情况下（demo默认），图片的尺寸应该为1080：2248（屏幕宽高比），但是现查询图片实际的尺寸是3024：4032

**Comment by RmondJone** [comment]
具体的你看代码，默认取得是设备支持的图片最大尺寸，你可以修改那边的逻辑取与屏幕相近的尺寸。另外相机拍出的照片不一定就是屏幕的分辨率，这点你就理解错了，你可以试试系统相机拍个照你就懂了。

**Comment by GIVEWAYTO** [comment]
好的，我这边找到setPictureSize，setPreviewSize两个方法，打印的参数值是640，1280。我再看看有没有其他相关的代码。另现在demo中的fileprovide是设置有问题的  

<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="com.rmondjone.camera.fileprovider"
            android:grantUriPermissions="true"
            android:exported="false">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_provider_paths" />
        </provider>
正确的是这样，demo中的标签弄反了

**Comment by GIVEWAYTO** [comment]
<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="com.rmondjone.camera.fileprovider"
            android:grantUriPermissions="true"
            android:exported="false">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_provider_paths" />
        </provider>

**Comment by GIVEWAYTO** [comment]
android:name="android.support.v4.content.FileProvider"
            android:authorities="com.rmondjone.camera.fileprovider"

**Comment by RmondJone** [comment]
你代码应该不是最新的，拉下最新代码，我今天刚刚提交。已经换成AndroidX了
